#!/usr/bin/env bash

set_all_fan_speeds ()
{
    cardcount="0";
    for CurrentCard in  /sys/class/drm/card?/ ; do
         for CurrentMonitor in "$CurrentCard"device/hwmon/hwmon?/ ; do
              cd $CurrentMonitor # &>/dev/null
              workingdir="`pwd`"

         cardcount="$(($cardcount + 1))"
    done
}

set_fans_requested ()
{
    if [ "$adapter"="all" ] ; then
        set_all_fan_speeds
    fi
}