from PyQt4 import QtCore, QtGui
from pyqtgraph import QtGui
import pyqtgraph


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1298, 733)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tab_widget = QtGui.QTabWidget(self.centralwidget)
        self.tab_widget.setMinimumSize(QtCore.QSize(600, 200))
        self.tab_widget.setStyleSheet(_fromUtf8(""))
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.process_tab_widget = QtGui.QWidget()
        self.process_tab_widget.setObjectName(_fromUtf8("process_tab_widget"))
        self.gridLayout = QtGui.QGridLayout(self.process_tab_widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.total_mem_frame = QtGui.QFrame(self.process_tab_widget)
        self.total_mem_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.total_mem_frame.setMaximumSize(QtCore.QSize(80, 40))
        self.total_mem_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/ram_total2.png);"))
        self.total_mem_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.total_mem_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.total_mem_frame.setObjectName(_fromUtf8("total_mem_frame"))
        self.horizontalLayout.addWidget(self.total_mem_frame)
        self.total_mem_label = QtGui.QLabel(self.process_tab_widget)
        self.total_mem_label.setMinimumSize(QtCore.QSize(120, 40))
        self.total_mem_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.total_mem_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid gray;\n"
"}"))
        self.total_mem_label.setObjectName(_fromUtf8("total_mem_label"))
        self.horizontalLayout.addWidget(self.total_mem_label)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.process_mem_graph = pyqtgraph.PlotWidget(self.process_tab_widget)
        self.process_mem_graph.setMinimumSize(QtCore.QSize(0, 0))
        self.process_mem_graph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.process_mem_graph.setStyleSheet(_fromUtf8("QWidget {\n"
"    border: 1px solid gray;\n"
"    padding: 1px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}"))
        self.process_mem_graph.setObjectName(_fromUtf8("process_mem_graph"))
        self.gridLayout.addWidget(self.process_mem_graph, 0, 1, 3, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.free_mem_frame = QtGui.QFrame(self.process_tab_widget)
        self.free_mem_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.free_mem_frame.setMaximumSize(QtCore.QSize(80, 40))
        self.free_mem_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/ram_free.png);"))
        self.free_mem_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.free_mem_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.free_mem_frame.setObjectName(_fromUtf8("free_mem_frame"))
        self.horizontalLayout_5.addWidget(self.free_mem_frame)
        self.free_mem_label = QtGui.QLabel(self.process_tab_widget)
        self.free_mem_label.setMinimumSize(QtCore.QSize(120, 40))
        self.free_mem_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.free_mem_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid gray;\n"
"}\n"
""))
        self.free_mem_label.setObjectName(_fromUtf8("free_mem_label"))
        self.horizontalLayout_5.addWidget(self.free_mem_label)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.swap_mem_frame = QtGui.QFrame(self.process_tab_widget)
        self.swap_mem_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.swap_mem_frame.setMaximumSize(QtCore.QSize(80, 40))
        self.swap_mem_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/ram_swap.png);"))
        self.swap_mem_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.swap_mem_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.swap_mem_frame.setObjectName(_fromUtf8("swap_mem_frame"))
        self.horizontalLayout_6.addWidget(self.swap_mem_frame)
        self.swap_mem_label = QtGui.QLabel(self.process_tab_widget)
        self.swap_mem_label.setMinimumSize(QtCore.QSize(120, 40))
        self.swap_mem_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.swap_mem_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid gray;\n"
"}"))
        self.swap_mem_label.setObjectName(_fromUtf8("swap_mem_label"))
        self.horizontalLayout_6.addWidget(self.swap_mem_label)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(1255, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 3)
        self.process_table_widget = QtGui.QTableWidget(self.process_tab_widget)
        self.process_table_widget.setMinimumSize(QtCore.QSize(0, 380))
        self.process_table_widget.setStyleSheet(_fromUtf8("QTableWidget {\n"
"    border: 1px solid gray;\n"
"    padding: 1px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}"))
        self.process_table_widget.setObjectName(_fromUtf8("process_table_widget"))
        self.process_table_widget.setColumnCount(5)
        self.process_table_widget.setRowCount(0)
        self.process_header = self.process_table_widget.horizontalHeader()
        self.process_header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(1, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(2, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(3, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(4, QtGui.QHeaderView.Stretch)
        self.process_table_widget.setHorizontalHeaderLabels(['Process', 'User', 'CPU%', 'MEM%', 'PID'])
        self.process_table_widget.setVerticalHeaderLabels([None])
        self.gridLayout.addWidget(self.process_table_widget, 4, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(1340, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 2)
        self.end_task_pushbutton = QtGui.QPushButton(self.process_tab_widget)
        self.end_task_pushbutton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.end_task_pushbutton.setStyleSheet(_fromUtf8("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid gray;\n"
"    padding: 3px;\n"
"}"))
        self.end_task_pushbutton.setObjectName(_fromUtf8("end_task_pushbutton"))
        self.gridLayout.addWidget(self.end_task_pushbutton, 5, 2, 1, 1)
        self.total_mem_frame.raise_()
        self.free_mem_frame.raise_()
        self.swap_mem_frame.raise_()
        self.free_mem_frame.raise_()
        self.end_task_pushbutton.raise_()
        self.process_mem_graph.raise_()
        self.tab_widget.addTab(self.process_tab_widget, _fromUtf8(""))
        self.cpu_tab_widget = QtGui.QWidget()
        self.cpu_tab_widget.setObjectName(_fromUtf8("cpu_tab_widget"))
        self.formLayout = QtGui.QFormLayout(self.cpu_tab_widget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cpu_temp_frame = QtGui.QFrame(self.cpu_tab_widget)
        self.cpu_temp_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.cpu_temp_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/thermometer-512.png);"))
        self.cpu_temp_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cpu_temp_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.cpu_temp_frame.setObjectName(_fromUtf8("cpu_temp_frame"))
        self.horizontalLayout_2.addWidget(self.cpu_temp_frame)
        self.cpu_temp_label = QtGui.QLabel(self.cpu_tab_widget)
        self.cpu_temp_label.setMinimumSize(QtCore.QSize(120, 40))
        self.cpu_temp_label.setMaximumSize(QtCore.QSize(130, 40))
        self.cpu_temp_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid black;\n"
"}"))
        self.cpu_temp_label.setObjectName(_fromUtf8("cpu_temp_label"))
        self.horizontalLayout_2.addWidget(self.cpu_temp_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cpu_fan_frame = QtGui.QFrame(self.cpu_tab_widget)
        self.cpu_fan_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.cpu_fan_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/cpu_fan.png);"))
        self.cpu_fan_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cpu_fan_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.cpu_fan_frame.setObjectName(_fromUtf8("cpu_fan_frame"))
        self.horizontalLayout_3.addWidget(self.cpu_fan_frame)
        self.cpu_fan_speed_label = QtGui.QLabel(self.cpu_tab_widget)
        self.cpu_fan_speed_label.setMinimumSize(QtCore.QSize(120, 40))
        self.cpu_fan_speed_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid black;\n"
"}"))
        self.cpu_fan_speed_label.setObjectName(_fromUtf8("cpu_fan_speed_label"))
        self.horizontalLayout_3.addWidget(self.cpu_fan_speed_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(1059, 89, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtGui.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(1255, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtGui.QFormLayout.SpanningRole, spacerItem3)
        self.cpu_table_widget = QtGui.QTableWidget(self.cpu_tab_widget)
        self.cpu_table_widget.setObjectName(_fromUtf8("cpu_table_widget"))
        self.cpu_table_widget.setColumnCount(0)
        self.cpu_table_widget.setRowCount(0)
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.cpu_table_widget)
        self.cpu_graph_widget = pyqtgraph.PlotWidget(self.cpu_tab_widget)
        self.cpu_graph_widget.setMinimumSize(QtCore.QSize(0, 300))
        self.cpu_graph_widget.setObjectName(_fromUtf8("cpu_graph_widget"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.cpu_graph_widget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.cpu_tab_widget)
        self.frame_3.setMinimumSize(QtCore.QSize(60, 50))
        self.frame_3.setStyleSheet(_fromUtf8("image: url(:/newPrefix/cpu.png);"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.cpu_load_progressbar = QtGui.QProgressBar(self.cpu_tab_widget)
        self.cpu_load_progressbar.setStyleSheet(_fromUtf8("QProgressBar {\n"
"    border: 2px solid black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"    border-bottom-right-radius:  6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-top-left-radius: 6px;\n"
"    font-size: 16px;\n"
"}"))
        self.cpu_load_progressbar.setProperty("value", 24)
        self.cpu_load_progressbar.setObjectName(_fromUtf8("cpu_load_progressbar"))
        self.horizontalLayout_4.addWidget(self.cpu_load_progressbar)
        self.formLayout.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.tab_widget.addTab(self.cpu_tab_widget, _fromUtf8(""))
        self.gpu_tab_widget = QtGui.QWidget()
        self.gpu_tab_widget.setObjectName(_fromUtf8("gpu_tab_widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gpu_tab_widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gpu_graph_widget = pyqtgraph.PlotWidget(self.gpu_tab_widget)
        self.gpu_graph_widget.setMinimumSize(QtCore.QSize(1050, 200))
        self.gpu_graph_widget.setObjectName(_fromUtf8("gpu_graph_widget"))
        self.gridLayout_2.addWidget(self.gpu_graph_widget, 0, 0, 5, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.gpu_clock_frame = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_clock_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_clock_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_clock_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/gpu.png);"))
        self.gpu_clock_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_clock_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_clock_frame.setObjectName(_fromUtf8("gpu_clock_frame"))
        self.horizontalLayout_7.addWidget(self.gpu_clock_frame)
        self.gpu_clock_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_clock_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_clock_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_clock_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid gray;\n"
"}"))
        self.gpu_clock_label.setObjectName(_fromUtf8("gpu_clock_label"))
        self.horizontalLayout_7.addWidget(self.gpu_clock_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gpu_mem_frame = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_mem_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_mem_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_mem_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/ram.png);"))
        self.gpu_mem_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_mem_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_mem_frame.setObjectName(_fromUtf8("gpu_mem_frame"))
        self.horizontalLayout_8.addWidget(self.gpu_mem_frame)
        self.gpu_mem_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_mem_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_mem_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_mem_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid gray\n"
"}"))
        self.gpu_mem_label.setObjectName(_fromUtf8("gpu_mem_label"))
        self.horizontalLayout_8.addWidget(self.gpu_mem_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.gpu_temp_frame = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_temp_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_temp_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_temp_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/thermometer-512.png);"))
        self.gpu_temp_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_temp_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_temp_frame.setObjectName(_fromUtf8("gpu_temp_frame"))
        self.horizontalLayout_9.addWidget(self.gpu_temp_frame)
        self.gpu_temp_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_temp_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_temp_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_temp_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid gray;\n"
"}"))
        self.gpu_temp_label.setObjectName(_fromUtf8("gpu_temp_label"))
        self.horizontalLayout_9.addWidget(self.gpu_temp_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gpu_watts_frame = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_watts_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_watts_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_watts_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/watts.png);"))
        self.gpu_watts_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_watts_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_watts_frame.setObjectName(_fromUtf8("gpu_watts_frame"))
        self.horizontalLayout_10.addWidget(self.gpu_watts_frame)
        self.gpu_watts_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_watts_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_watts_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_watts_label.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid gray;\n"
"}"))
        self.gpu_watts_label.setObjectName(_fromUtf8("gpu_watts_label"))
        self.horizontalLayout_10.addWidget(self.gpu_watts_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)
        self.gpu_fcurve_checkbox = QtGui.QCheckBox(self.gpu_tab_widget)
        self.gpu_fcurve_checkbox.setObjectName(_fromUtf8("gpu_fcurve_checkbox"))
        self.gridLayout_2.addWidget(self.gpu_fcurve_checkbox, 4, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(1255, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 2)
        self.gpu_fan_progressbar = QtGui.QProgressBar(self.gpu_tab_widget)
        self.gpu_fan_progressbar.setStyleSheet(_fromUtf8("QProgressBar {\n"
"    border: 2px solid black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    font-size: 16px;\n"
"}"))
        self.gpu_fan_progressbar.setProperty("value", 24)
        self.gpu_fan_progressbar.setObjectName(_fromUtf8("gpu_fan_progressbar"))
        self.gridLayout_2.addWidget(self.gpu_fan_progressbar, 6, 0, 1, 2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.gpu_fan_Frame = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_fan_Frame.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_fan_Frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/cpu_fan.png);"))
        self.gpu_fan_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_fan_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_fan_Frame.setObjectName(_fromUtf8("gpu_fan_Frame"))
        self.horizontalLayout_11.addWidget(self.gpu_fan_Frame)
        self.gpu_fan_slider = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_fan_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_fan_slider.setObjectName(_fromUtf8("gpu_fan_slider"))
        self.horizontalLayout_11.addWidget(self.gpu_fan_slider)
        self.gpu_cfan_checkbox = QtGui.QCheckBox(self.gpu_tab_widget)
        self.gpu_cfan_checkbox.setObjectName(_fromUtf8("gpu_cfan_checkbox"))
        self.horizontalLayout_11.addWidget(self.gpu_cfan_checkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 7, 0, 1, 2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.gpu_clock_frame_2 = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_clock_frame_2.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_clock_frame_2.setStyleSheet(_fromUtf8("image: url(:/newPrefix/cpu.png);"))
        self.gpu_clock_frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_clock_frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_clock_frame_2.setObjectName(_fromUtf8("gpu_clock_frame_2"))
        self.horizontalLayout_12.addWidget(self.gpu_clock_frame_2)
        self.gpu_clock_sliderbar = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_clock_sliderbar.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_clock_sliderbar.setObjectName(_fromUtf8("gpu_clock_sliderbar"))
        self.horizontalLayout_12.addWidget(self.gpu_clock_sliderbar)
        self.gpu_oc_checkbox = QtGui.QCheckBox(self.gpu_tab_widget)
        self.gpu_oc_checkbox.setObjectName(_fromUtf8("gpu_oc_checkbox"))
        self.horizontalLayout_12.addWidget(self.gpu_oc_checkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 8, 0, 1, 2)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.gpu_memoc_frame = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_memoc_frame.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_memoc_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/ram.png);"))
        self.gpu_memoc_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_memoc_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_memoc_frame.setObjectName(_fromUtf8("gpu_memoc_frame"))
        self.horizontalLayout_13.addWidget(self.gpu_memoc_frame)
        self.gpu_mem_sliderbar = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_mem_sliderbar.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_mem_sliderbar.setObjectName(_fromUtf8("gpu_mem_sliderbar"))
        self.horizontalLayout_13.addWidget(self.gpu_mem_sliderbar)
        self.gpu_adaptive_radio = QtGui.QRadioButton(self.gpu_tab_widget)
        self.gpu_adaptive_radio.setObjectName(_fromUtf8("gpu_adaptive_radio"))
        self.horizontalLayout_13.addWidget(self.gpu_adaptive_radio)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 9, 0, 1, 2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.gpu_ocwatts_frame = QtGui.QFrame(self.gpu_tab_widget)
        self.gpu_ocwatts_frame.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_ocwatts_frame.setStyleSheet(_fromUtf8("image: url(:/newPrefix/watts.png);"))
        self.gpu_ocwatts_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpu_ocwatts_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gpu_ocwatts_frame.setObjectName(_fromUtf8("gpu_ocwatts_frame"))
        self.horizontalLayout_14.addWidget(self.gpu_ocwatts_frame)
        self.gpu_watts_sliderbar = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_watts_sliderbar.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_watts_sliderbar.setObjectName(_fromUtf8("gpu_watts_sliderbar"))
        self.horizontalLayout_14.addWidget(self.gpu_watts_sliderbar)
        self.gpu_performance_radio = QtGui.QRadioButton(self.gpu_tab_widget)
        self.gpu_performance_radio.setMinimumSize(QtCore.QSize(0, 30))
        self.gpu_performance_radio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gpu_performance_radio.setObjectName(_fromUtf8("gpu_performance_radio"))
        self.horizontalLayout_14.addWidget(self.gpu_performance_radio)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 10, 0, 1, 2)
        self.tab_widget.addTab(self.gpu_tab_widget, _fromUtf8(""))
        self.network_tab_widget = QtGui.QWidget()
        self.network_tab_widget.setObjectName(_fromUtf8("network_tab_widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.network_tab_widget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.net_process_widget = QtGui.QTableWidget(self.network_tab_widget)
        self.net_process_widget.setObjectName(_fromUtf8("net_process_widget"))
        self.net_process_widget.setColumnCount(3)
        self.net_process_widget.setRowCount(0)
        self.net_header = self.net_process_widget.horizontalHeader()
        self.net_header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        self.net_header.setResizeMode(1, QtGui.QHeaderView.Stretch)
        self.net_header.setResizeMode(2, QtGui.QHeaderView.Stretch)
        self.net_process_widget.setHorizontalHeaderLabels(['Application', 'Download', 'Upload'])
        self.gridLayout_4.addWidget(self.net_process_widget, 0, 0, 1, 1)
        self.net_speed_graph = pyqtgraph.PlotWidget(self.network_tab_widget)
        self.net_speed_graph.setMinimumSize(QtCore.QSize(600, 0))
        self.net_speed_graph.setObjectName(_fromUtf8("net_speed_graph"))
        self.gridLayout_4.addWidget(self.net_speed_graph, 0, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(1129, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 0, 1, 2)
        self.net_limit_pushbutton = QtGui.QPushButton(self.network_tab_widget)
        self.net_limit_pushbutton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.net_limit_pushbutton.setStyleSheet(_fromUtf8("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid gray;\n"
"    padding: 3px;\n"
"}"))
        self.net_limit_pushbutton.setObjectName(_fromUtf8("net_limit_pushbutton"))
        self.gridLayout_4.addWidget(self.net_limit_pushbutton, 1, 2, 1, 1)
        self.tab_widget.addTab(self.network_tab_widget, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tab_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Complete System Monitor", None))
        self.total_mem_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Total</span></p></body></html>", None))
        self.free_mem_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Free</span></p></body></html>", None))
        self.swap_mem_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Swap</span></p></body></html>", None))
        self.end_task_pushbutton.setText(_translate("MainWindow", "End Process", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.process_tab_widget), _translate("MainWindow", "Processes", None))
        self.cpu_temp_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Temp C</span></p></body></html>", None))
        self.cpu_fan_speed_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Cpu Fan </span></p></body></html>", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.cpu_tab_widget), _translate("MainWindow", "CPU", None))
        self.gpu_clock_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Gpu Speed</span></p></body></html>", None))
        self.gpu_mem_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">M Speed</span></p></body></html>", None))
        self.gpu_temp_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Gpu Temp</span></p></body></html>", None))
        self.gpu_watts_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Gpu Watts</span></p></body></html>", None))
        self.gpu_fcurve_checkbox.setText(_translate("MainWindow", "Fan Curve", None))
        self.gpu_cfan_checkbox.setText(_translate("MainWindow", "Manual Fan", None))
        self.gpu_oc_checkbox.setText(_translate("MainWindow", "Enable OC", None))
        self.gpu_adaptive_radio.setText(_translate("MainWindow", "Adaptive", None))
        self.gpu_performance_radio.setText(_translate("MainWindow", "Performance", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.gpu_tab_widget), _translate("MainWindow", "GPU", None))
        self.net_limit_pushbutton.setText(_translate("MainWindow", "Set Limit", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.network_tab_widget), _translate("MainWindow", "Network", None))

import images_rc


class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

