from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1310, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setMinimumSize(QtCore.QSize(600, 200))
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setObjectName("tab_widget")
        self.process_tab_widget = QtWidgets.QWidget()
        self.process_tab_widget.setObjectName("process_tab_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.process_tab_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.total_mem_frame = QtWidgets.QFrame(self.process_tab_widget)
        self.total_mem_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.total_mem_frame.setMaximumSize(QtCore.QSize(80, 40))
        self.total_mem_frame.setStyleSheet("image: url(:/newPrefix/ram_total2.png);")
        self.total_mem_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.total_mem_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.total_mem_frame.setObjectName("total_mem_frame")
        self.horizontalLayout.addWidget(self.total_mem_frame)
        self.total_mem_label = QtWidgets.QLabel(self.process_tab_widget)
        self.total_mem_label.setMinimumSize(QtCore.QSize(120, 40))
        self.total_mem_label.setMaximumSize(QtCore.QSize(120, 40))
        self.total_mem_label.setStyleSheet("QLabel {\n"
"    border: 1px solid gray;\n"
"}")
        self.total_mem_label.setObjectName("total_mem_label")
        self.horizontalLayout.addWidget(self.total_mem_label)
        self.horizontalLayout_15.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.free_mem_frame = QtWidgets.QFrame(self.process_tab_widget)
        self.free_mem_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.free_mem_frame.setMaximumSize(QtCore.QSize(80, 40))
        self.free_mem_frame.setStyleSheet("image: url(:/newPrefix/ram_free.png);")
        self.free_mem_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.free_mem_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.free_mem_frame.setObjectName("free_mem_frame")
        self.horizontalLayout_5.addWidget(self.free_mem_frame)
        self.free_mem_label = QtWidgets.QLabel(self.process_tab_widget)
        self.free_mem_label.setMinimumSize(QtCore.QSize(120, 40))
        self.free_mem_label.setMaximumSize(QtCore.QSize(120, 40))
        self.free_mem_label.setStyleSheet("QLabel {\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.free_mem_label.setObjectName("free_mem_label")
        self.horizontalLayout_5.addWidget(self.free_mem_label)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.swap_mem_frame = QtWidgets.QFrame(self.process_tab_widget)
        self.swap_mem_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.swap_mem_frame.setMaximumSize(QtCore.QSize(80, 40))
        self.swap_mem_frame.setStyleSheet("image: url(:/newPrefix/ram_swap.png);")
        self.swap_mem_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.swap_mem_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.swap_mem_frame.setObjectName("swap_mem_frame")
        self.horizontalLayout_6.addWidget(self.swap_mem_frame)
        self.swap_mem_label = QtWidgets.QLabel(self.process_tab_widget)
        self.swap_mem_label.setMinimumSize(QtCore.QSize(120, 40))
        self.swap_mem_label.setMaximumSize(QtCore.QSize(120, 40))
        self.swap_mem_label.setStyleSheet("QLabel {\n"
"    border: 1px solid gray;\n"
"}")
        self.swap_mem_label.setObjectName("swap_mem_label")
        self.horizontalLayout_6.addWidget(self.swap_mem_label)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_15, 0, 0, 1, 2)
        self.process_mem_graph = pyqtgraph.GraphicsLayoutWidget(self.process_tab_widget)
        self.process_mem_graph.setMinimumSize(QtCore.QSize(0, 275))
        self.process_mem_graph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.process_mem_graph.setStyleSheet("QWidget {\n"
"    border: 1px solid gray;\n"
"    padding: 1px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}")
        self.process_mem_graph.setObjectName("process_mem_graph")
        self.gridLayout.addWidget(self.process_mem_graph, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(1267, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        self.process_table_widget = QtWidgets.QTableWidget(self.process_tab_widget)
        self.process_table_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.process_table_widget.setStyleSheet("QTableWidget {\n"
"    border: 1px solid gray;\n"
"    padding: 1px;\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}")
        self.process_table_widget.setObjectName("process_table_widget")
        self.process_table_widget.setColumnCount(5)
        self.process_table_widget.setRowCount(0)
        self.process_header = self.process_table_widget.horizontalHeader()
        self.process_header.setSectionResizeMode(0, QtGui.QHeaderView.Stretch)
        self.process_header.setSectionResizeMode(1, QtGui.QHeaderView.Stretch)
        self.process_header.setSectionResizeMode(2, QtGui.QHeaderView.Stretch)
        self.process_header.setSectionResizeMode(3, QtGui.QHeaderView.Stretch)
        self.process_header.setSectionResizeMode(4, QtGui.QHeaderView.Stretch)
        self.process_table_widget.setHorizontalHeaderLabels(['Process', 'User', 'CPU%', 'MEM%', 'PID'])
        self.process_table_widget.setVerticalHeaderLabels([None])
        self.process_table_widget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.process_table_widget, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(1170, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.end_task_pushbutton = QtWidgets.QPushButton(self.process_tab_widget)
        self.end_task_pushbutton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.end_task_pushbutton.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid gray;\n"
"    padding: 3px;\n"
"}")
        self.end_task_pushbutton.setObjectName("end_task_pushbutton")
        self.gridLayout.addWidget(self.end_task_pushbutton, 4, 1, 1, 1)
        self.process_table_widget.raise_()
        self.end_task_pushbutton.raise_()
        self.process_mem_graph.raise_()
        self.tab_widget.addTab(self.process_tab_widget, "")
        self.cpu_tab_widget = QtWidgets.QWidget()
        self.cpu_tab_widget.setObjectName("cpu_tab_widget")
        self.formLayout = QtWidgets.QFormLayout(self.cpu_tab_widget)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cpu_temp_frame = QtWidgets.QFrame(self.cpu_tab_widget)
        self.cpu_temp_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.cpu_temp_frame.setStyleSheet("image: url(:/newPrefix/thermometer-512.png);")
        self.cpu_temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cpu_temp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_temp_frame.setObjectName("cpu_temp_frame")
        self.horizontalLayout_2.addWidget(self.cpu_temp_frame)
        self.cpu_temp_label = QtWidgets.QLabel(self.cpu_tab_widget)
        self.cpu_temp_label.setMinimumSize(QtCore.QSize(120, 40))
        self.cpu_temp_label.setMaximumSize(QtCore.QSize(130, 40))
        self.cpu_temp_label.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"}")
        self.cpu_temp_label.setObjectName("cpu_temp_label")
        self.horizontalLayout_2.addWidget(self.cpu_temp_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cpu_fan_frame = QtWidgets.QFrame(self.cpu_tab_widget)
        self.cpu_fan_frame.setMinimumSize(QtCore.QSize(60, 40))
        self.cpu_fan_frame.setStyleSheet("image: url(:/newPrefix/cpu_fan.png);")
        self.cpu_fan_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cpu_fan_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_fan_frame.setObjectName("cpu_fan_frame")
        self.horizontalLayout_3.addWidget(self.cpu_fan_frame)
        self.cpu_fan_speed_label = QtWidgets.QLabel(self.cpu_tab_widget)
        self.cpu_fan_speed_label.setMinimumSize(QtCore.QSize(120, 40))
        self.cpu_fan_speed_label.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"}")
        self.cpu_fan_speed_label.setObjectName("cpu_fan_speed_label")
        self.horizontalLayout_3.addWidget(self.cpu_fan_speed_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(1059, 89, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(1255, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cpu_table_widget = QtWidgets.QTableWidget(self.cpu_tab_widget)
        self.cpu_table_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.cpu_table_widget.setObjectName("cpu_table_widget")
        self.cpu_header = self.cpu_table_widget.horizontalHeader()
        self.cpu_table_widget.setColumnCount(0)
        self.cpu_table_widget.setRowCount(2)
        self.cpu_table_widget.setVerticalHeaderLabels(["MHz", "Percent"])
        self.verticalLayout_2.addWidget(self.cpu_table_widget)
        self.cpu_graph_widget = pyqtgraph.PlotWidget(self.cpu_tab_widget)
        self.cpu_graph_widget.setMinimumSize(QtCore.QSize(0, 400))
        self.cpu_graph_widget.setObjectName("cpu_graph_widget")
        self.verticalLayout_2.addWidget(self.cpu_graph_widget)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.cpu_tab_widget)
        self.frame_3.setMinimumSize(QtCore.QSize(60, 50))
        self.frame_3.setStyleSheet("image: url(:/newPrefix/cpu.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.cpu_load_progressbar = QtWidgets.QProgressBar(self.cpu_tab_widget)
        self.cpu_load_progressbar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"    border-bottom-right-radius:  6px;\n"
"    border-bottom-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-top-left-radius: 6px;\n"
"    font-size: 16px;\n"
"}")
        self.cpu_load_progressbar.setProperty("value", 24)
        self.cpu_load_progressbar.setObjectName("cpu_load_progressbar")
        self.horizontalLayout_4.addWidget(self.cpu_load_progressbar)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.tab_widget.addTab(self.cpu_tab_widget, "")
        self.gpu_tab_widget = QtWidgets.QWidget()
        self.gpu_tab_widget.setObjectName("gpu_tab_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gpu_tab_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gpu_clock_frame_2 = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_clock_frame_2.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_clock_frame_2.setStyleSheet("image: url(:/newPrefix/cpu.png);")
        self.gpu_clock_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_clock_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_clock_frame_2.setObjectName("gpu_clock_frame_2")
        self.horizontalLayout_12.addWidget(self.gpu_clock_frame_2)
        self.gpu_clock_sliderbar = QtWidgets.QSlider(self.gpu_tab_widget)
        self.gpu_clock_sliderbar.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_clock_sliderbar.setObjectName("gpu_clock_sliderbar")
        self.horizontalLayout_12.addWidget(self.gpu_clock_sliderbar)
        self.gpu_oc_checkbox = QtWidgets.QCheckBox(self.gpu_tab_widget)
        self.gpu_oc_checkbox.setObjectName("gpu_oc_checkbox")
        self.horizontalLayout_12.addWidget(self.gpu_oc_checkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 8, 0, 1, 2)
        self.gpu_fcurve_checkbox = QtWidgets.QCheckBox(self.gpu_tab_widget)
        self.gpu_fcurve_checkbox.setObjectName("gpu_fcurve_checkbox")
        self.gridLayout_2.addWidget(self.gpu_fcurve_checkbox, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(1255, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 2)
        self.gpu_fan_progressbar = QtWidgets.QProgressBar(self.gpu_tab_widget)
        self.gpu_fan_progressbar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid black;\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"    border-bottom-right-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    border-top-left-radius: 8px;\n"
"    border-bottom-left-radius: 8px;\n"
"    font-size: 16px;\n"
"}")
        self.gpu_fan_progressbar.setProperty("value", 24)
        self.gpu_fan_progressbar.setObjectName("gpu_fan_progressbar")
        self.gridLayout_2.addWidget(self.gpu_fan_progressbar, 6, 0, 1, 2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gpu_memoc_frame = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_memoc_frame.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_memoc_frame.setStyleSheet("image: url(:/newPrefix/ram.png);")
        self.gpu_memoc_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_memoc_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_memoc_frame.setObjectName("gpu_memoc_frame")
        self.horizontalLayout_13.addWidget(self.gpu_memoc_frame)
        self.gpu_mem_sliderbar = QtWidgets.QSlider(self.gpu_tab_widget)
        self.gpu_mem_sliderbar.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_mem_sliderbar.setObjectName("gpu_mem_sliderbar")
        self.horizontalLayout_13.addWidget(self.gpu_mem_sliderbar)
        self.gpu_adaptive_radio = QtWidgets.QRadioButton(self.gpu_tab_widget)
        self.gpu_adaptive_radio.setObjectName("gpu_adaptive_radio")
        self.horizontalLayout_13.addWidget(self.gpu_adaptive_radio)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 9, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gpu_mem_frame = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_mem_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_mem_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_mem_frame.setStyleSheet("image: url(:/newPrefix/ram.png);")
        self.gpu_mem_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_mem_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_mem_frame.setObjectName("gpu_mem_frame")
        self.horizontalLayout_8.addWidget(self.gpu_mem_frame)
        self.gpu_mem_label = QtWidgets.QLabel(self.gpu_tab_widget)
        self.gpu_mem_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_mem_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_mem_label.setStyleSheet("QLabel {\n"
"    border: 1px solid gray\n"
"}")
        self.gpu_mem_label.setObjectName("gpu_mem_label")
        self.horizontalLayout_8.addWidget(self.gpu_mem_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gpu_ocwatts_frame = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_ocwatts_frame.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_ocwatts_frame.setStyleSheet("image: url(:/newPrefix/watts.png);")
        self.gpu_ocwatts_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_ocwatts_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_ocwatts_frame.setObjectName("gpu_ocwatts_frame")
        self.horizontalLayout_14.addWidget(self.gpu_ocwatts_frame)
        self.gpu_watts_sliderbar = QtWidgets.QSlider(self.gpu_tab_widget)
        self.gpu_watts_sliderbar.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_watts_sliderbar.setObjectName("gpu_watts_sliderbar")
        self.horizontalLayout_14.addWidget(self.gpu_watts_sliderbar)
        self.gpu_performance_radio = QtWidgets.QRadioButton(self.gpu_tab_widget)
        self.gpu_performance_radio.setMinimumSize(QtCore.QSize(0, 30))
        self.gpu_performance_radio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gpu_performance_radio.setObjectName("gpu_performance_radio")
        self.horizontalLayout_14.addWidget(self.gpu_performance_radio)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 10, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gpu_watts_frame = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_watts_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_watts_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_watts_frame.setStyleSheet("image: url(:/newPrefix/watts.png);")
        self.gpu_watts_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_watts_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_watts_frame.setObjectName("gpu_watts_frame")
        self.horizontalLayout_10.addWidget(self.gpu_watts_frame)
        self.gpu_watts_label = QtWidgets.QLabel(self.gpu_tab_widget)
        self.gpu_watts_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_watts_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_watts_label.setStyleSheet("QLabel {\n"
"    border: 1px solid gray;\n"
"}")
        self.gpu_watts_label.setObjectName("gpu_watts_label")
        self.horizontalLayout_10.addWidget(self.gpu_watts_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gpu_fan_Frame = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_fan_Frame.setMinimumSize(QtCore.QSize(40, 0))
        self.gpu_fan_Frame.setStyleSheet("image: url(:/newPrefix/cpu_fan.png);")
        self.gpu_fan_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_fan_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_fan_Frame.setObjectName("gpu_fan_Frame")
        self.horizontalLayout_11.addWidget(self.gpu_fan_Frame)
        self.gpu_fan_slider = QtWidgets.QSlider(self.gpu_tab_widget)
        self.gpu_fan_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_fan_slider.setObjectName("gpu_fan_slider")
        self.horizontalLayout_11.addWidget(self.gpu_fan_slider)
        self.gpu_cfan_checkbox = QtWidgets.QCheckBox(self.gpu_tab_widget)
        self.gpu_cfan_checkbox.setObjectName("gpu_cfan_checkbox")
        self.horizontalLayout_11.addWidget(self.gpu_cfan_checkbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 7, 0, 1, 2)
        self.gpu_graph_widget = pyqtgraph.PlotWidget(self.gpu_tab_widget)
        self.gpu_graph_widget.setXRange(0, 90, padding=0.006)
        self.gpu_graph_widget.setYRange(0, 100, padding=0.006)
        self.gpu_graph_widget.setLabel('left', 'Fanspeed', units='%')
        self.gpu_graph_widget.setLabel('bottom', 'Temp', units='C')
        self.gpu_graph_widget.showGrid(x=True, y=True, alpha=1)
        self.gpu_graph_widget.setMouseTracking(True)
        self.gpu_graph_widget.setMinimumSize(QtCore.QSize(1050, 200))
        self.gpu_graph_widget.setObjectName("gpu_graph_widget")
        self.gridLayout_2.addWidget(self.gpu_graph_widget, 0, 0, 5, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gpu_clock_frame = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_clock_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_clock_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_clock_frame.setStyleSheet("image: url(:/newPrefix/gpu.png);")
        self.gpu_clock_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_clock_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_clock_frame.setObjectName("gpu_clock_frame")
        self.horizontalLayout_7.addWidget(self.gpu_clock_frame)
        self.gpu_clock_label = QtWidgets.QLabel(self.gpu_tab_widget)
        self.gpu_clock_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_clock_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_clock_label.setStyleSheet("QLabel {\n"
"    border: 1px solid gray;\n"
"}")
        self.gpu_clock_label.setObjectName("gpu_clock_label")
        self.horizontalLayout_7.addWidget(self.gpu_clock_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gpu_temp_frame = QtWidgets.QFrame(self.gpu_tab_widget)
        self.gpu_temp_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.gpu_temp_frame.setMaximumSize(QtCore.QSize(60, 16777215))
        self.gpu_temp_frame.setStyleSheet("image: url(:/newPrefix/thermometer-512.png);")
        self.gpu_temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gpu_temp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gpu_temp_frame.setObjectName("gpu_temp_frame")
        self.horizontalLayout_9.addWidget(self.gpu_temp_frame)
        self.gpu_temp_label = QtWidgets.QLabel(self.gpu_tab_widget)
        self.gpu_temp_label.setMinimumSize(QtCore.QSize(60, 40))
        self.gpu_temp_label.setMaximumSize(QtCore.QSize(110, 40))
        self.gpu_temp_label.setStyleSheet("QLabel {\n"
"    border: 1px solid gray;\n"
"}")
        self.gpu_temp_label.setObjectName("gpu_temp_label")
        self.horizontalLayout_9.addWidget(self.gpu_temp_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.tab_widget.addTab(self.gpu_tab_widget, "")
        self.network_tab_widget = QtWidgets.QWidget()
        self.network_tab_widget.setObjectName("network_tab_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.network_tab_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.net_process_widget = QtWidgets.QTableWidget(self.network_tab_widget)
        self.net_process_widget.setObjectName("net_process_widget")
        self.net_process_widget.setColumnCount(3)
        self.net_process_widget.setRowCount(0)
        self.net_header = self.net_process_widget.horizontalHeader()
        self.net_header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        self.net_header.setResizeMode(1, QtGui.QHeaderView.Stretch)
        self.net_header.setResizeMode(2, QtGui.QHeaderView.Stretch)
        self.net_process_widget.setHorizontalHeaderLabels(['Application', 'Download', 'Upload'])
        self.net_process_widget.setVerticalHeaderLabels([None])
        self.net_process_widget.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.net_process_widget, 0, 0, 1, 1)
        self.net_speed_graph = pyqtgraph.PlotWidget(self.network_tab_widget)
        self.net_speed_graph.setMinimumSize(QtCore.QSize(600, 0))
        self.net_speed_graph.setObjectName("net_speed_graph")
        self.gridLayout_4.addWidget(self.net_speed_graph, 0, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(1129, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 0, 1, 2)
        self.net_limit_pushbutton = QtWidgets.QPushButton(self.network_tab_widget)
        self.net_limit_pushbutton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.net_limit_pushbutton.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    border: 2px solid gray;\n"
"    padding: 3px;\n"
"}")
        self.net_limit_pushbutton.setObjectName("net_limit_pushbutton")
        self.gridLayout_4.addWidget(self.net_limit_pushbutton, 1, 2, 1, 1)
        self.tab_widget.addTab(self.network_tab_widget, "")
        self.gridLayout_3.addWidget(self.tab_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Complete System Monitor"))
        self.total_mem_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Total</span></p></body></html>"))
        self.free_mem_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Free</span></p></body></html>"))
        self.swap_mem_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Swap</span></p></body></html>"))
        self.end_task_pushbutton.setText(_translate("MainWindow", "End Process"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.process_tab_widget), _translate("MainWindow", "Processes"))
        self.cpu_temp_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Temp C</span></p></body></html>"))
        self.cpu_fan_speed_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Cpu Fan </span></p></body></html>"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.cpu_tab_widget), _translate("MainWindow", "CPU"))
        self.gpu_oc_checkbox.setText(_translate("MainWindow", "Manual OC"))
        self.gpu_fcurve_checkbox.setText(_translate("MainWindow", "Set Fancurve"))
        self.gpu_adaptive_radio.setText(_translate("MainWindow", "Adaptive"))
        self.gpu_mem_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">M Speed</span></p></body></html>"))
        self.gpu_performance_radio.setText(_translate("MainWindow", "Performance"))
        self.gpu_watts_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Gpu Watts</span></p></body></html>"))
        self.gpu_cfan_checkbox.setText(_translate("MainWindow", "Manual Fan"))
        self.gpu_clock_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Gpu Speed</span></p></body></html>"))
        self.gpu_temp_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Gpu Temp</span></p></body></html>"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.gpu_tab_widget), _translate("MainWindow", "GPU"))
        self.net_limit_pushbutton.setText(_translate("MainWindow", "Set Limit"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.network_tab_widget), _translate("MainWindow", "Network"))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
