from PyQt4 import QtCore, QtGui
from pyqtgraph import QtGui
import pyqtgraph

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.process_tab_widget = QtGui.QWidget()
        self.process_tab_widget.setObjectName(_fromUtf8("process_tab_widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.process_tab_widget)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.process_table_widget = QtGui.QTableWidget(self.process_tab_widget)
        self.process_table_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.process_table_widget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.process_table_widget.setGridStyle(QtCore.Qt.SolidLine)
        self.process_table_widget.setColumnCount(5)
        self.process_header = self.process_table_widget.horizontalHeader()
        self.process_header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(1, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(2, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(3, QtGui.QHeaderView.Stretch)
        self.process_header.setResizeMode(4, QtGui.QHeaderView.Stretch)

        self.process_table_widget.setHorizontalHeaderLabels(['Process', 'User', 'CPU%', 'MEM%', 'PID'])
        self.process_table_widget.setVerticalHeaderLabels([None])



        self.process_table_widget.setObjectName(_fromUtf8("process_table_widget"))
        self.process_table_widget.setRowCount(0)
        self.process_table_widget.horizontalHeader().setStretchLastSection(True)
        self.process_table_widget.verticalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.process_table_widget, 2, 0, 1, 3)
        self.end_process_pushbutton = QtGui.QPushButton(self.process_tab_widget)
        self.end_process_pushbutton.setObjectName(_fromUtf8("end_process_pushbutton"))
        self.gridLayout_2.addWidget(self.end_process_pushbutton, 1, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.total_memory_lcd = QtGui.QLCDNumber(self.process_tab_widget)
        self.total_memory_lcd.setMinimumSize(QtCore.QSize(0, 36))
        self.total_memory_lcd.setMaximumSize(QtCore.QSize(16777215, 40))

        self.total_memory_lcd.setObjectName(_fromUtf8("total_memory_lcd"))
        self.verticalLayout.addWidget(self.total_memory_lcd)
        self.free_memory_lcd = QtGui.QLCDNumber(self.process_tab_widget)
        self.free_memory_lcd.setMinimumSize(QtCore.QSize(0, 36))
        self.free_memory_lcd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.free_memory_lcd.setObjectName(_fromUtf8("free_memory_lcd"))
        self.verticalLayout.addWidget(self.free_memory_lcd)
        self.total_swap_lcd = QtGui.QLCDNumber(self.process_tab_widget)
        self.total_swap_lcd.setMinimumSize(QtCore.QSize(0, 36))
        self.total_swap_lcd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.total_swap_lcd.setObjectName(_fromUtf8("total_swap_lcd"))
        self.verticalLayout.addWidget(self.total_swap_lcd)
        self.free_swap_lcd = QtGui.QLCDNumber(self.process_tab_widget)
        self.free_swap_lcd.setMinimumSize(QtCore.QSize(0, 36))
        self.free_swap_lcd.setMaximumSize(QtCore.QSize(16777215, 45))
        self.free_swap_lcd.setObjectName(_fromUtf8("free_swap_lcd"))
        self.verticalLayout.addWidget(self.free_swap_lcd)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.total_memory_label = QtGui.QLabel(self.process_tab_widget)
        self.total_memory_label.setObjectName(_fromUtf8("total_memory_label"))
        self.verticalLayout_2.addWidget(self.total_memory_label)
        self.free_memory_label = QtGui.QLabel(self.process_tab_widget)
        self.free_memory_label.setObjectName(_fromUtf8("free_memory_label"))
        self.verticalLayout_2.addWidget(self.free_memory_label)
        self.swap_memory_label = QtGui.QLabel(self.process_tab_widget)
        self.swap_memory_label.setObjectName(_fromUtf8("swap_memory_label"))
        self.verticalLayout_2.addWidget(self.swap_memory_label)
        self.used_swap_memory_label = QtGui.QLabel(self.process_tab_widget)
        self.used_swap_memory_label.setObjectName(_fromUtf8("used_swap_memory_label"))
        self.verticalLayout_2.addWidget(self.used_swap_memory_label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 2, 2)
        self.tabWidget.addTab(self.process_tab_widget, _fromUtf8(""))
        self.cpu_tab_widget = QtGui.QWidget()
        self.cpu_tab_widget.setObjectName(_fromUtf8("cpu_tab_widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.cpu_tab_widget)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.cpu_fan_speed_lcd = QtGui.QLCDNumber(self.cpu_tab_widget)
        self.cpu_fan_speed_lcd.setMinimumSize(QtCore.QSize(0, 36))
        self.cpu_fan_speed_lcd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cpu_fan_speed_lcd.setObjectName(_fromUtf8("lcdNumber"))
        self.verticalLayout_3.addWidget(self.cpu_fan_speed_lcd)
        self.cpu_temp_lcd = QtGui.QLCDNumber(self.cpu_tab_widget)
        self.cpu_temp_lcd.setMinimumSize(QtCore.QSize(0, 36))
        self.cpu_temp_lcd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.cpu_temp_lcd.setObjectName(_fromUtf8("lcdNumber_2"))
        self.verticalLayout_3.addWidget(self.cpu_temp_lcd)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cpu_fan_speed_label = QtGui.QLabel(self.cpu_tab_widget)
        self.cpu_fan_speed_label.setObjectName(_fromUtf8("cpu_fan_speed_label"))
        self.verticalLayout_4.addWidget(self.cpu_fan_speed_label)
        self.cpu_temp_label = QtGui.QLabel(self.cpu_tab_widget)
        self.cpu_temp_label.setObjectName(_fromUtf8("cpu_temp_label"))
        self.verticalLayout_4.addWidget(self.cpu_temp_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 2, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cpu_load_label = QtGui.QLabel(self.cpu_tab_widget)
        self.cpu_load_label.setObjectName(_fromUtf8("cpu_load_label"))
        self.horizontalLayout_3.addWidget(self.cpu_load_label)
        self.cpu_load_progressbar = QtGui.QProgressBar(self.cpu_tab_widget)
        self.cpu_load_progressbar.setProperty("value", 24)
        self.cpu_load_progressbar.setObjectName(_fromUtf8("cpu_load_progressbar"))
        self.horizontalLayout_3.addWidget(self.cpu_load_progressbar)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.cpu_percentage_graph = pyqtgraph.PlotWidget(self.cpu_tab_widget)
        self.cpu_percentage_graph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cpu_percentage_graph.setObjectName(_fromUtf8("cpu_percentage_graph"))
        self.gridLayout_3.addWidget(self.cpu_percentage_graph, 3, 0, 1, 2)
        self.tabWidget.addTab(self.cpu_tab_widget, _fromUtf8(""))
        self.gpu_tab_widget = QtGui.QWidget()
        self.gpu_tab_widget.setObjectName(_fromUtf8("gpu_tab_widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gpu_tab_widget)
        self.gridLayout_4.setMargin(11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gpu_fancurve_graph = pyqtgraph.PlotWidget(self.gpu_tab_widget)
        self.gpu_fancurve_graph.setObjectName(_fromUtf8("gpu_fancurve_graph"))
        self.gridLayout_4.addWidget(self.gpu_fancurve_graph, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gpu_clock_speed_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_clock_speed_label.setObjectName(_fromUtf8("gpu_clock_speed_label"))
        self.verticalLayout_6.addWidget(self.gpu_clock_speed_label)
        self.gpu_mem_speed_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_mem_speed_label.setObjectName(_fromUtf8("gpu_mem_speed_label"))
        self.verticalLayout_6.addWidget(self.gpu_mem_speed_label)
        self.gpu_watts_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_watts_label.setObjectName(_fromUtf8("gpu_watts_label"))
        self.verticalLayout_6.addWidget(self.gpu_watts_label)
        self.gpu_temp_label = QtGui.QLabel(self.gpu_tab_widget)
        self.gpu_temp_label.setObjectName(_fromUtf8("gpu_temp_label"))
        self.verticalLayout_6.addWidget(self.gpu_temp_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gpu_clock_lcd = QtGui.QLCDNumber(self.gpu_tab_widget)
        self.gpu_clock_lcd.setMinimumSize(QtCore.QSize(0, 0))
        self.gpu_clock_lcd.setObjectName(_fromUtf8("gpu_clock_lcd"))
        self.verticalLayout_5.addWidget(self.gpu_clock_lcd)
        self.gpu_mem_lcd = QtGui.QLCDNumber(self.gpu_tab_widget)
        self.gpu_mem_lcd.setMinimumSize(QtCore.QSize(0, 0))
        self.gpu_mem_lcd.setObjectName(_fromUtf8("gpu_mem_lcd"))
        self.verticalLayout_5.addWidget(self.gpu_mem_lcd)
        self.gpu_watts_lcd = QtGui.QLCDNumber(self.gpu_tab_widget)
        self.gpu_watts_lcd.setObjectName(_fromUtf8("gpu_watts_lcd"))
        self.verticalLayout_5.addWidget(self.gpu_watts_lcd)
        self.gpu_temp_lcd = QtGui.QLCDNumber(self.gpu_tab_widget)
        self.gpu_temp_lcd.setObjectName(_fromUtf8("gpu_temp_lcd"))
        self.verticalLayout_5.addWidget(self.gpu_temp_lcd)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 1, 2, 1)
        self.gpu_fan_speed_progressbar = QtGui.QProgressBar(self.gpu_tab_widget)
        self.gpu_fan_speed_progressbar.setProperty("value", 24)
        self.gpu_fan_speed_progressbar.setObjectName(_fromUtf8("gpu_fan_speed_progressbar"))
        self.gridLayout_4.addWidget(self.gpu_fan_speed_progressbar, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.set_gpu_fan_speed_label = QtGui.QLabel(self.gpu_tab_widget)
        self.set_gpu_fan_speed_label.setObjectName(_fromUtf8("set_gpu_fan_speed_label"))
        self.verticalLayout_7.addWidget(self.set_gpu_fan_speed_label)
        self.set_gpu_clock_speed_label = QtGui.QLabel(self.gpu_tab_widget)
        self.set_gpu_clock_speed_label.setObjectName(_fromUtf8("set_gpu_clock_speed_label"))
        self.verticalLayout_7.addWidget(self.set_gpu_clock_speed_label)
        self.set_gpu_mem_speed_label = QtGui.QLabel(self.gpu_tab_widget)
        self.set_gpu_mem_speed_label.setObjectName(_fromUtf8("set_gpu_mem_speed_label"))
        self.verticalLayout_7.addWidget(self.set_gpu_mem_speed_label)
        self.set_gpu_watts_label = QtGui.QLabel(self.gpu_tab_widget)
        self.set_gpu_watts_label.setObjectName(_fromUtf8("set_gpu_watts_label"))
        self.verticalLayout_7.addWidget(self.set_gpu_watts_label)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gpu_fan_speed_slider = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_fan_speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_fan_speed_slider.setObjectName(_fromUtf8("gpu_fan_speed_slider"))
        self.verticalLayout_8.addWidget(self.gpu_fan_speed_slider)
        self.gpu_clock_slider = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_clock_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_clock_slider.setObjectName(_fromUtf8("gpu_clock_slider"))
        self.verticalLayout_8.addWidget(self.gpu_clock_slider)
        self.gpu_mem_slider = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_mem_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_mem_slider.setObjectName(_fromUtf8("gpu_mem_slider"))
        self.verticalLayout_8.addWidget(self.gpu_mem_slider)
        self.gpu_watts_slider = QtGui.QSlider(self.gpu_tab_widget)
        self.gpu_watts_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gpu_watts_slider.setObjectName(_fromUtf8("gpu_watts_slider"))
        self.verticalLayout_8.addWidget(self.gpu_watts_slider)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setMargin(11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.manual_fanspeed_checkbox = QtGui.QCheckBox(self.gpu_tab_widget)
        self.manual_fanspeed_checkbox.setObjectName(_fromUtf8("manual_fanspeed_checkbox"))
        self.verticalLayout_9.addWidget(self.manual_fanspeed_checkbox)
        self.fancurve_checkbox = QtGui.QCheckBox(self.gpu_tab_widget)
        self.fancurve_checkbox.setObjectName(_fromUtf8("fancurve_checkbox"))
        self.verticalLayout_9.addWidget(self.fancurve_checkbox)
        self.manual_overclocking_checkbox = QtGui.QCheckBox(self.gpu_tab_widget)
        self.manual_overclocking_checkbox.setObjectName(_fromUtf8("manual_overclocking_checkbox"))
        self.verticalLayout_9.addWidget(self.manual_overclocking_checkbox)
        self.adaptive_oc_radio = QtGui.QRadioButton(self.gpu_tab_widget)
        self.adaptive_oc_radio.setObjectName(_fromUtf8("adaptive_oc_radio"))
        self.verticalLayout_9.addWidget(self.adaptive_oc_radio)
        self.performance_oc_radio = QtGui.QRadioButton(self.gpu_tab_widget)
        self.performance_oc_radio.setObjectName(_fromUtf8("performance_oc_radio"))
        self.verticalLayout_9.addWidget(self.performance_oc_radio)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 2, 0, 1, 2)
        self.tabWidget.addTab(self.gpu_tab_widget, _fromUtf8(""))
        self.network_tab_widget = QtGui.QWidget()
        self.network_tab_widget.setObjectName(_fromUtf8("network_tab_widget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.network_tab_widget)
        self.gridLayout_5.setMargin(11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.network_table_widget = QtGui.QTableWidget(self.network_tab_widget)
        self.network_table_widget.setRowCount(0)
        self.network_table_widget.setColumnCount(3)
        self.network_table_widget.setObjectName(_fromUtf8("network_table_widget"))
        self.network_table_widget.setHorizontalHeaderLabels(['Application', 'Download', 'Upload'])
        self.header = self.network_table_widget.horizontalHeader()
        self.header.setResizeMode(0, QtGui.QHeaderView.Stretch)
        self.header.setResizeMode(1, QtGui.QHeaderView.Stretch)
        self.header.setResizeMode(2, QtGui.QHeaderView.Stretch)
        self.vertical_header = self.network_table_widget.verticalHeader()
        self.vertical_header.setResizeMode(QtGui.QHeaderView.Stretch)
      #  self.header.setResizeMode(0, QtGui.QHeaderView.ResizeToContents)
       # self.header.setResizeMode(1, QtGui.QHeaderView.ResizeToContents)
        #self.header.setResizeMode(2, QtGui.QHeaderView.ResizeToContents)

        self.horizontalLayout_6.addWidget(self.network_table_widget)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(671, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.network_limit_pushbutton = QtGui.QPushButton(self.network_tab_widget)
        self.network_limit_pushbutton.setObjectName(_fromUtf8("network_limit_pushbutton"))
        self.gridLayout_5.addWidget(self.network_limit_pushbutton, 1, 1, 1, 1)
        self.tabWidget.addTab(self.network_tab_widget, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Complete System Monitor", None))
        self.end_process_pushbutton.setText(_translate("MainWindow", "End Process", None))
        self.total_memory_label.setText(_translate("MainWindow", "Total Memory", None))
        self.free_memory_label.setText(_translate("MainWindow", "Free Memory", None))
        self.swap_memory_label.setText(_translate("MainWindow", "Swap Memory", None))
        self.used_swap_memory_label.setText(_translate("MainWindow", "Used Swap Memory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.process_tab_widget), _translate("MainWindow", "Processes", None))
        self.cpu_fan_speed_label.setText(_translate("MainWindow", "CPU Fan Speed RPM", None))
        self.cpu_temp_label.setText(_translate("MainWindow", "CPU Temperature C", None))
        self.cpu_load_label.setText(_translate("MainWindow", "CPU Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cpu_tab_widget), _translate("MainWindow", "CPU", None))
        self.gpu_clock_speed_label.setText(_translate("MainWindow", "Clock Speed", None))
        self.gpu_mem_speed_label.setText(_translate("MainWindow", "Mem Speed", None))
        self.gpu_watts_label.setText(_translate("MainWindow", "Watts", None))
        self.gpu_temp_label.setText(_translate("MainWindow", "Temp C", None))
        self.set_gpu_fan_speed_label.setText(_translate("MainWindow", "Fan Speed", None))
        self.set_gpu_clock_speed_label.setText(_translate("MainWindow", "Clock Speed", None))
        self.set_gpu_mem_speed_label.setText(_translate("MainWindow", "Memory Speed", None))
        self.set_gpu_watts_label.setText(_translate("MainWindow", "Power Watts", None))
        self.manual_fanspeed_checkbox.setText(_translate("MainWindow", "Enable Manual Fan Speed", None))
        self.fancurve_checkbox.setText(_translate("MainWindow", "Enable Fan Curve", None))
        self.manual_overclocking_checkbox.setText(_translate("MainWindow", "Enable Manual Overclocking", None))
        self.adaptive_oc_radio.setText(_translate("MainWindow", "Adapti&ve", None))
        self.performance_oc_radio.setText(_translate("MainWindow", "Perfor&mance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gpu_tab_widget), _translate("MainWindow", "GPU", None))
        self.network_limit_pushbutton.setText(_translate("MainWindow", "Set Limit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.network_tab_widget), _translate("MainWindow", "Network", None))


class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

